chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='chat'),
    path('<str:room>/<str:user>/<str:passw>/', views.room, name='room'),
    path('chat/join/',views.join,name='join'),
    path('chat/edit_room/<str:room>/<str:passw>/',views.EditRoom,name='edit_room'),
]

chat1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/',include('chat.urls')),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    room = models.CharField(max_length=200)
    password=models.CharField(max_length=200)
    descrtiption = models.TextField(default='New Room')

    def __str__(self):
        return str(self.room)


class Message(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    user = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.room)

chat/forms.py
from django import forms
from .models import Room

class RoomForm(forms.ModelForm):
	class Meta:
		model = Room
		fields='__all__'

class EditRoom(forms.ModelForm):
	class Meta:
		model = Room
		fields = ['room','password']

chat/views.py
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.decorators import login_required
from .models import Message,Room
import random,string
import base64
from django.contrib.auth.models import User
import json
import random
import hashlib
from django.views.decorators.csrf import csrf_exempt
from .forms import RoomForm,EditRoom
from django.contrib.auth.models import User

@csrf_exempt
@login_required(login_url='login')
def index(request):
    show_presentation_list = []
    room_presentation=[]
    abc = None
    page = User.objects.get(username=request.user)
    mess = Message.objects.filter(user=request.user)
    for m in mess:
        if m.room not in show_presentation_list:
            show_presentation_list.append(m.room)
            room_presentation.append(m)
    form = RoomForm(request.POST or None)
    if request.method =='POST':
        if form.is_valid():
            name = form.cleaned_data['room']
            passw = form.cleaned_data['password']
            print(passw)
            print(name)
            room = name
            Room.objects.get_or_create(room=name,password=passw)
            abc = Room.objects.get(room=name,password=passw)
            return redirect(reverse('room',kwargs={'room':name,'user':request.user,'passw':passw}))
    room_presentaions = map(base64.b64encode,room_presentation)
    return render(request, 'chat/index.html',{'abc':abc,'username':page,'room_presentation':room_presentation,'form':form})


@login_required(login_url='login')  
def room(request,room,user,passw):
    show_presentation_list = []
    room_presentation=[]
    users = User.objects.all()
    name = Room.objects.get(room=room,password=passw)
    print(name)
    page = User.objects.get(username=request.user)
    mess = Message.objects.filter(user=request.user)
    for m in mess:
        if m.room not in show_presentation_list:
            show_presentation_list.append(m.room)
            room_presentation.append(m)

    names = request.GET.get('username')
    messages=Message.objects.filter(room=name)[0:25]
    mess = Message.objects.all()
    return render(request, 'chat/room.html', {'name':name,'users':users,'username': request.user.username,'room_name':room,'messages': messages,'mess':mess ,'room_presentation':room_presentation,'passw':passw})



def join(request):
    ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    chars=[]
    for i in range(16):
        chars.append(random.choice(ALPHABET))
    "".join(chars)
    show_presentation_list = []
    room_presentation=[]
    page = User.objects.get(username=request.user)
    abc = None
    mess = Message.objects.filter(user=request.user)
    for m in mess:
        if m.room not in show_presentation_list:
            show_presentation_list.append(m.room)
            room_presentation.append(m)
            joined_rooms = Room.objects.get(room=m.room)
            abc=joined_rooms
            print(abc)
            
    print(room_presentation)
    return render(request, 'chat/join.html',{'abc':abc,'username':page,'chars':chars,'room_presentation':room_presentation})



@login_required(login_url='login')
def EditRoom(request,room,passw):
    room = Room.objects.get(room=room,password=passw)
    print(room)
    form = RoomForm(request.POST or None,request.FILES or None, instance=room)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('room',kwargs={'room':room,'user':request.user,'passw':passw}))
    return render(request,'chat/edit_room.html',{'form':form})


@login_required(login_url='login')
def DeleteRoom(request,room,passw):
    room = Room.objects.get(room=room,password=passw)
    print(room)
    form = RoomForm(request.POST or None,request.FILES or None, instance=room)
    if request.method=='POST':
        if form.is_valid():
            form.save()

    return render(request,'chat/edit_room.html',{'form':form})



def country(request,country):
    country = User.objects.filter(country=country)
    return render(request,'posts/country.html',{'country':country})

chat/templates/chat/edit_room.html
{% load crispy_forms_tags %}


	<form method="POST" enctype=multipart/form-data>
		{% csrf_token %}
		{{form|crispy}}
		<button class="ui inverted green button"> submit</button>
	</form>
	<br>
	

chat/templates/chat/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

    <head>
      <style type="text/css">
        /* change the background color */
        .navbar-custom {
            background-color: #ff5500;
        }
        /* change the brand and text color */
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
            color: rgba(255,255,255,.8);
        }
        /* change the link color */
        .navbar-custom .navbar-nav .nav-link {
            color: rgba(255,255,255,.5);
        }
        /* change the color of active or hovered links */
        .navbar-custom .nav-item.active .nav-link,
        .navbar-custom .nav-item:focus .nav-link,
        .navbar-custom .nav-item:hover .nav-link {
            color: #FFCC99;
        }
      </style>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/material-ui/5.0.0-alpha.38/index.js" integrity="sha512-+/CE3rUMAHHxIE4eb3rUteWf2ZsSTzzJOfHRsH2PqK5DmIqXKouo1sNYs4t06MewYNPhZc0m+oyioweaOGOUnA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="http://www.myersdaily.org/joseph/javascript/md5.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{%static 'caretaker/cropperjs/dist/cropper.min.css' %}">
      <script  src="{%static 'caretaker/cropperjs/dist/cropper.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
      <script src="{% static 'caretaker/cropperjs/base.js'%}"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css"> 
      <style type="text/css">

      </style>
    </head>
    <body>
        <main role="main" >
          <div class="container container-fluid">
        <section class="section">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16"  class="position top-0 start-100">
                    <a href="{%url 'join' %}">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                    </a>
                </svg>    
            </div>
            <div class="container">
                

                    <div class="column is-4 is-offset-4">
                        
                        <div class="field">

                            <label> Create Or Join Existing Chat Room</label>
                            
                            <div class="control">

                              <form method="POST">
                                {%csrf_token%}
                                {{form|crispy}}
                                <input class="input" type="hidden" placeholder="Username" id="username-input" value="{{username}}">
                                <br>
                                <br>
                                <button class="btn btn-primary" id="room-name-submit">Submit</button>
                              </form>
                            </div>
                        </div>

                        <div class="field">
                            <label></label>

                            <div class="control">
                                
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <script src="http://www.myersdaily.org/joseph/javascript/md5.js"></script>
        <script>
            document.querySelector('#room-name-submit').onclick = function(e) {
                var roomName = document.querySelector('#id_room').value;
                var userName = document.querySelector('#username-input').value;
                var password = document.querySelector('#id_password').value;

                function stringToHash(string) {
                  
                var hash = 0;
                  
                if (string.length == 0) return hash;
                  
                for (i = 0; i < string.length; i++) {
                    char = string.charCodeAt(i);
                    hash = ((hash << 5) - hash) + char;
                    hash = hash & hash;
                }
                  
                return hash;
            }

                window.location.replace(roomName + '/?'+userName+'/'+password);
            };
        </script>
          </div>
        </main>

    </body>
</html>

chat/templates/chat/join.html
        <div>
            <p>Recent Groups</p>
            <div class="container container-fluid"></div>
                {% for room in room_presentation %}
                    <ul role="presentation">
                        <div class="container">
                            <a href="{%url 'room' room=room.room user=request.user passw=abc.password%}"><p id="room-name ">{{room.room}}</p></a>
                        </div>
                    </ul>
                {% endfor %}
            </div>

        </div>

chat/templates/chat/live_audio.html
{%extends 'caretaker/base.html'%}
{%load static%}
{%block content%}

  
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Live Streaming</title>
        <style type="text/css">

        #remote-container{
            display: flex;
                position: relative;
                width: 600px;
                height: 400px;
                border: 2px solid black;
        }
        #remote-container video{
            height: auto;
            position: relative !important;
                position: absolute;
                right: -20px;
                width: 100px;
                height: 120px;
                border: 2px solid black;
        }
            
        </style>
        <script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-3.6.1.js"></script>
    </head>
    <body>
        {{ room_name|json_script:"json-roomname" }}
        {{ username|json_script:"json-username" }}
        <h1>
            SneekHub<br>
        </h1>
        <label id="label-channel_name"></label>
        <form method="POST">
            {%csrf_token%}
            <input type="hidden" id="channel_name" placeholder="Channel Name" name="channel_name" value="{{room}}">
            
        </form>
        
        {% for user in user_presentation %}
            <ul role="presentation">
                <div class="container">
                    {%if request.user.username == user.user%}
                        <p>me</p>
                    {%else%}
                        <p id="user">{{user.user}}</p>
                    {%endif%}     
                </div>
            </ul>
        {% endfor %}
        <input type="hidden" id="username1" name="username1" value="{{username}}">
        <button id="host">Host</button>
        <button onclick="startCall('audience')" id="audience">Audience</button>
        <button id="mute">Mute </button>
        <input type="text" id="music_file" placeholder="enter the file path">
        <button id="play-music">playFile</button>
        <button id="leave-call">Leave</button>
        {{ request.user.username|json_script:"user_id" }}
        <div id="me">
            <p id="alldata"></p>
        </div>
        <h4>Remote video</h4>
        
        <div class="container">
          <div class="row">
            <div class="col-xs-12 board" id="remote-container"></div>   
          </div>
        </div>
        <script type="text/javascript">
            const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
            const userName = JSON.parse(document.getElementById('json-username').textContent);
            console.log(userName)
        </script>
        <script src="{%static 'stream/stream.js'%}"></script>
    </body>
    </html>
{%endblock%}

    

chat/templates/chat/stream.html
{%load static%}

  
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Live Streaming</title>
    <style type="text/css">
    span{
      max-height: 200px;
      overflow-y: scroll; 
      display: block
    }
    p {
      content: '\a';
      white-space: pre-line;
      display: block;
    }
    b.bold_text {
      font-weight: bold;
    }
    *{
		  font-family: sans-serif;
		}
		h1,h4{
		    text-align: center;
		}
		#me{
		    position: relative;
		    width: 50%;
		    margin: 0 auto;
		    display: block;
		}
		#me video{
		    position: relative !important;
		}
		#remote-container{
		    display: flex;
		}
		#remote-container video{
		    height: auto;
		    position: relative !important;
		}
    </style>
    <script src="https://cdn.agora.io/sdk/release/AgoraRTCSDK-3.6.1.js"></script>
</head>
<body>
    <input type="text" id="channel_name" placeholder="Channel Name">

    <button onclick="startCall('host')" id="host">Host</button>
    <button onclick="startCall('audience')" id="audience">Audience</button>
    <input type="text" id="music_file" placeholder="enter the file path">
    <button onclick="playMusic()">playFile</button>
    <h4>Local video</h4>
    <div id="me"></div>
    <h4>Remote video</h4>
    <div id="remote-container">
    </div>

    <script src="{%static 'stream/stream.js'%}"></script>
</body>
</html>

chat/templates/chat/stream_index.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>Sneeky Chat</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    </head>

    <body>
        <section class="section">
            <div class="container">
                <div class="columns is-multiline">
                    <div class="column is-6 is-offset-3 mb-6">
                        <section class="hero is-primary">
                            <div class="hero-body">
                                <p class="title">
                                    Sneeky
                                </p>

                                
                            </div>
                        </section>
                    </div>

                    <div class="column is-4 is-offset-4">
                        <div class="field">
                            <label>Room name</label>
                            
                            <div class="control">
                                <input class="input" type="text" placeholder="Room name" id="room-name-input" value="">
                            </div>
                        </div>

                        <div class="field">
                            <label></label>

                            <div class="control">
                                <input class="input" type="hidden" placeholder="Username" id="username-input" value="{{username}}">
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <a class="button is-info" id="room-name-submit">Submit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script>
            document.querySelector('#room-name-submit').onclick = function(e) {
                var roomName = document.querySelector('#room-name-input').value;
                var userName = document.querySelector('#username-input').value;

                window.location.replace(roomName + '/?username=' +userName);
            };
        </script>
    </body>
</html>